#!/bin/sh

# Copyright 2016 Brocade Communications Systems, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

curl -k -H "St2-Api-Key: ZDVhNGM0M2RmMDJjZWEzOGZjZWZlMWYzNzExMTFiNTJiZmU1ODk0ZjY1Zjc3YTMxNGFkMDg2N2RlNDgyMzg0NA" \
	-H "Content-Type: application/json" \
	-X POST --data '{"trigger": "campus-ztp.dhcp_commit", "payload": {"client_ip": "10.10.10.50","remote_id": "74:8e:f8:63:d:80","subscriber_id": "","circuit_id": "1/23","hostname": "ICX7750-48F-Switchcc4e.246e.0c80","client_mac": "cc:4e:24:6e:c:80"}}' \
	https://localhost/api/v1/webhooks/dhcpcommit
